name: CI-CD

on:
    push:
        branches:
            - main

jobs:
    test:
        name:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout

    build:
        name:
        runs-on: ubuntu-latest
        steps:
