name: CI-CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.6
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
                
            - name: Install dependencies
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests with pytest
              run: |
                pytest --html=report.html

            - name: Upload de artefatos
              uses: actions/upload-artifact@v3
              with:
                name: test
                path: |
                  report.html
                  assets
             
    build:

        needs: test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          
          - name: Set up Python 3.6
            uses: actions/setup-python@v5
            with:
              python-version: "3.x"

          - name: Build com pyinstaller
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pyinstaller --onefile calculator.py

          - name: Upload de artefatos
            uses: actions/upload-artifact@v3
            with:
              name: run
              path: dist/main.exe
